### PR TITLE
Bug 27261 - [Custom]: definition construction algorithm step 6 makes no ...

### PR DESCRIPTION
**Pull request by dglazkov**
...sense

https://www.w3.org/Bugs/Public/show_bug.cgi?id=27261

### CODE REVIEW

**Comment by dglazkov** [comment]
Not yet :smile: Still lots of work to do on this bug.

**Comment by hayatoito** [comment]
Ops. Sorry for that. We shouldn't merge a pull request unless merge is explicitly requested. :)

**Comment by hayatoito** [comment]
May I revert the commit?

**Comment by dglazkov** [comment]
It's okay. I will patch over it.

**Pull request merged**
