### PR TITLE
Move Reference Target Explainer from AOM repository

### PR DESCRIPTION
**Pull request by behowell**
This document explains the proposed Reference Target feature. It originally came out of the AOM group due to its importance for ARIA and accessibility. However, since it is a shadow-dom-specific feature with implications for web components beyond just accessibility, it makes more sense for it to move to the web components group.

This document currently lives in the AOM repository here: https://github.com/WICG/aom/blob/gh-pages/reference-target-explainer.md. I'm replacing the contents of that file with a link to this new file, in PR https://github.com/WICG/aom/pull/211, so there only exists one current copy of this explainer.

If you have comments on the content of the proposal itself, please log an issue or PR against this explainer once it is merged, rather than adding a comment on this PR. I'd like to get the file moved before making revisions. Thanks!

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

**Review by keithamus — APPROVED** [review]
LGTM 👍

**Review by nolanlawson — APPROVED** [review]

**Review by Westbrook — APPROVED** [review]

**Comment by behowell** [comment]
Thanks all for the approvals! It looks like I still need an approval from someone with write access. @Westbrook do you know who would be good to ping about that?

**Comment by Westbrook** [comment]
@rniwa would you be able to take a look at this?

**Comment by dandclark** [comment]
@marcoscaceres or @cwilso would you be able to help here? The AOM group would like to move this proposal to WICG for further incubation but I'm not sure who can merge the explainer to this repo. Doesn't seem like there's been a lot of activity here lately.

**Comment by dandclark** [comment]
@annevk Are you able to merge this explainer? Any chance we can widen the scope of people who have write access here so we can iterate on this more effectively?

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
I've asked an admin to increase the set of people with write access.

**Pull request merged**
