### PR TITLE
Proposed change for active element algorithm.

### PR DESCRIPTION
**Pull request by TakayoshiKochi**
Discussed in https://github.com/w3c/webcomponents/issues/358

### CODE REVIEW

**Comment by TakayoshiKochi** [comment]
@hayatoito PTAL

**Comment by hayatoito** [comment]
Looks okay. However, the equivalent algorithm can be expressed by adding a few lines to the current algorithm:
1.   Let ADJUSTED be the result of the retargeting algorithm with ROOT and ELEMENT as input
2.   If ROOT is not the root node of ADJUSTED:
   1. Let ADJUSTED be null

I prefer this because this express the intention more clearly, IMO.

**Comment by rniwa** [comment]
It seems premature to make this change given there is a disagreement on what `activeElement` should do.

**Comment by TakayoshiKochi** [comment]
@hayatoito It looks good. I'm not sure if this algorithm having any dependency on changes in event retargeting algorithm, but as they are in the same spec it should not be a problem for any consistency.

@rniwa okay, will wait for other parties.

**Comment by hayatoito** [comment]
I have named it "retargeting algorithm", instead of "event retargeting algorithm", because the concept of _retargeting_ is not for only for an event. This algorithm is intentionally written as a general algorithm so that we can re-use it from other places where we need a retargeting, such as activeElement here.

**Comment by TakayoshiKochi** [comment]
@hayato got it.  The new patch has "retargeting algorithm", as you suggested.

**Comment by hayatoito** [comment]
It looks outdated. Closing.

**Pull request closed without merging**
