### PR TITLE
Add link to Templates spec

### PR DESCRIPTION
**Pull request by zenorocha**

### CODE REVIEW

**Comment by hayatoito** [comment]
The template spec has graduated and has been merged to HTML living standard.

http://www.whatwg.org/specs/web-apps/current-work/multipage/scripting-1.html#the-template-element

**Comment by zenorocha** [comment]
So are you guys going to remove it from this repo?

**Comment by hayatoito** [comment]
Yes. That should be removed to avoid a confusion.

**Comment by zenorocha** [comment]
But isn't Templates "part" of Web Components?

**Comment by hayatoito** [comment]
No longer, IMO. I guess there are outdated documents.
They should link to http://www.whatwg.org/specs/web-apps/current-work/multipage/scripting-1.html#the-template-element.

**Comment by hayatoito** [comment]
Anyway, thank you for your attention! We have a lot of things to be cleaned up. :)

**Pull request closed without merging**
